#!/bin/sh -x
# $Id: Check,v 1.1 2011-03-24 17:23:13-07 - - $
#
# Make sure the program cid is in your path.
#
rm hello
make spotless    >spotless.log 2>&1
make ci          >ci.log 2>&1
make all         >all.log 2>&1
